#!/usr/bin/env bash
set -euo pipefail

# Compare two environment reports generated by check_ros2_env.sh.
# Usage:
#   ./environment_check/compare_env_reports.sh file_a.txt file_b.txt
#   ./environment_check/compare_env_reports.sh   # auto-pick latest 2 reports

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${BASE_DIR}/environment_check"

pick_latest_two() {
  local files=()
  while IFS= read -r f; do
    files+=("$f")
  done < <(ls -1t "${OUT_DIR}"/env_*.txt 2>/dev/null || true)

  if [ "${#files[@]}" -lt 2 ]; then
    echo "错误: 环境报告不足2个，无法自动对比。" >&2
    echo "请先在两台电脑上执行 ./environment_check/check_ros2_env.sh" >&2
    exit 1
  fi
  printf '%s\n%s\n' "${files[0]}" "${files[1]}"
}

extract_value() {
  local key="$1"
  local file="$2"
  local value
  if [[ "${key}" == *":" ]]; then
    value="$(
      awk -v k="${key}" '
        index($0, "- " k) == 1 {
          sub("^- " k "[[:space:]]*", "", $0)
          print
          exit
        }
      ' "${file}"
    )"
  else
    value="$(
      awk -v k="${key}" '
        $0 == "## " k {in_section=1; next}
        /^## / && in_section {exit}
        in_section && NF {print; exit}
      ' "${file}"
    )"
  fi
  if [ -z "${value}" ]; then
    value="(not found)"
  fi
  printf '%s' "${value}"
}

if [ "$#" -eq 2 ]; then
  FILE_A="$1"
  FILE_B="$2"
else
  mapfile -t latest < <(pick_latest_two)
  FILE_A="${latest[0]}"
  FILE_B="${latest[1]}"
fi

if [ ! -f "${FILE_A}" ] || [ ! -f "${FILE_B}" ]; then
  echo "错误: 输入文件不存在。" >&2
  echo "A=${FILE_A}" >&2
  echo "B=${FILE_B}" >&2
  exit 1
fi

echo "# Environment Compare Result"
echo ""
echo "- File A: ${FILE_A}"
echo "- File B: ${FILE_B}"
echo ""

KEYS=(
  "generated_at:"
  "hostname:"
  "ROS_DISTRO (env)"
  "ROS_VERSION (env)"
  "ROS_PYTHON_VERSION (env)"
  "ros2 path"
  "ros2 cli package version"
  "ROS2 packages (dpkg)"
  "Python"
  "Colcon"
  "RMW implementation"
  "ROS domain id"
)

for key in "${KEYS[@]}"; do
  A_VAL="$(extract_value "${key}" "${FILE_A}")"
  B_VAL="$(extract_value "${key}" "${FILE_B}")"

  echo "## ${key}"
  echo "- A: ${A_VAL}"
  echo "- B: ${B_VAL}"
  if [ "${A_VAL}" = "${B_VAL}" ]; then
    echo "- Match: YES"
  else
    echo "- Match: NO"
  fi
  echo ""
done
